### ISSUE TITLE
Any plan to update to Swift 3.0?

### ISSUE THREAD

**Issue by hujunfeng** [danthorpe/ValueCoding#23]
I tried to update ValueCoding to Swift 3.0 by myself, but encountered a segmentation fault from Swift compiler:

```
Command failed due to signal: Segmentation fault: 11
```

I'm not sure how to fix this, so want to ask, do you have any plan to update the project to Swift 3.0?

Thanks.

**Comment by danthorpe** [comment]
Hi @hujunfeng - absolutely want to update _ValueCoding_ to Swift 3.0. The problem is, that it crashes. I raised a radar when the first Beta was out - still crashing in Xcode 8 GM. I'll have to see if I can get some Swift compiler developers to look into it though.

It's not even really clear why it crashes.

**Comment by hujunfeng** [comment]
@danthorpe thank you for the reply.

I didn't notice there is a [swift/3.0_tmp](https://github.com/danthorpe/ValueCoding/tree/swift/3.0_tmp) branch previously. I gave a try of that branch in my project, it doesn't crash and seems working fine. I'm running Xcode 8.0 (8A218a).

**Comment by danthorpe** [comment]
Oh really? Okay - I will revisit :)

**Comment by danthorpe** [comment]
Done! See version 2.0.0 🚀
